# Site settings
title: Banter bloguje
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog o softwarovém inženýrství, programování v jazycích Java či Groovy,
  ale i o mimopracovních věcech, které mi přeletí přes nos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.zvestov.cz" # the base hostname & protocol for your site
twitter_username: banterCZ
#github_username:  jekyll

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
paginate: 10
exclude:
  - README.md
  - Gemfile.lock
  - Gemfile

#Plugins
gems:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-twitter-plugin
